/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as SelecionarPlanoRouteImport } from './routes/selecionar-plano'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PrevisaoRouteImport } from './routes/previsao'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BancosRouteImport } from './routes/bancos'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecionarPlanoRoute = SelecionarPlanoRouteImport.update({
  id: '/selecionar-plano',
  path: '/selecionar-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisaoRoute = PrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BancosRoute = BancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/bancos': typeof BancosRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/previsao': typeof PrevisaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/selecionar-plano': typeof SelecionarPlanoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/bancos': typeof BancosRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/previsao': typeof PrevisaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/selecionar-plano': typeof SelecionarPlanoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/bancos': typeof BancosRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/previsao': typeof PrevisaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/selecionar-plano': typeof SelecionarPlanoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/bancos'
    | '/cadastro'
    | '/configuracoes'
    | '/esqueci-senha'
    | '/fluxo-de-caixa'
    | '/login'
    | '/metas'
    | '/previsao'
    | '/relatorios'
    | '/reset-senha'
    | '/selecionar-plano'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/bancos'
    | '/cadastro'
    | '/configuracoes'
    | '/esqueci-senha'
    | '/fluxo-de-caixa'
    | '/login'
    | '/metas'
    | '/previsao'
    | '/relatorios'
    | '/reset-senha'
    | '/selecionar-plano'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/bancos'
    | '/cadastro'
    | '/configuracoes'
    | '/esqueci-senha'
    | '/fluxo-de-caixa'
    | '/login'
    | '/metas'
    | '/previsao'
    | '/relatorios'
    | '/reset-senha'
    | '/selecionar-plano'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  BancosRoute: typeof BancosRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  PrevisaoRoute: typeof PrevisaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetSenhaRoute: typeof ResetSenhaRoute
  SelecionarPlanoRoute: typeof SelecionarPlanoRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecionar-plano': {
      id: '/selecionar-plano'
      path: '/selecionar-plano'
      fullPath: '/selecionar-plano'
      preLoaderRoute: typeof SelecionarPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsao': {
      id: '/previsao'
      path: '/previsao'
      fullPath: '/previsao'
      preLoaderRoute: typeof PrevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bancos': {
      id: '/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof BancosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  BancosRoute: BancosRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  PrevisaoRoute: PrevisaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetSenhaRoute: ResetSenhaRoute,
  SelecionarPlanoRoute: SelecionarPlanoRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
